[CMake] require urdfdom >= 0.4.0
As on centos7's urdfdom v0.3.0:
src/parsers/urdf/model.cpp:43:45: error: 'InertialSharedPtr' in
namespace 'urdf' does not name a type